# Generated by Django 5.1.3 on 2024-12-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
