# Generated by Django 5.1.4 on 2024-12-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shopitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('ShopItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shopitem')),
            ],
        ),
    ]
