# Generated by Django 5.1.4 on 2025-02-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='intrests',
            new_name='interest',
        ),
    ]
