# Generated by Django 5.1.4 on 2025-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_shopitem_category_remove_rating_shopitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
