# Generated by Django 5.1.4 on 2025-02-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_shopitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
